const recomendadosJSON = [
  {
    id: 1,
    img: "./image/61NsX0xdNSL._AC_UF1000,1000_QL80_.jpg",
    categoria: "SOFTWARE",
    nombre: "Rocket League",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 599,
    precioF: 999,
    iframe: "https://www.youtube.com/embed/SgSX3gOrj60?si=0eNHjSW8c1PbF5Zt",
  },
  {
    id: 2,
    img: "./image/eldenringxbox.jpg",
    categoria: "SOFTWARE",
    nombre: "ELDEN RING",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 1200,
    precioF: 1399,
    iframe: "https://www.youtube.com/embed/CptaXqVY6-E?si=VLFR1ljxEpWGVMVp",
  },
  {
    id: 3,
    img: "./image/reddead.jpg",
    categoria: "SOFTWARE",
    nombre: "RED DEAD REDEMPTION II",
    plataforma: "PS4",
    estado: "NUEVO",
    precio: 599,
    precioF: 999,
    iframe: "https://www.youtube.com/embed/eaW0tYpxyp0?si=hqWHVI19o1jvmCyr",
  },
  {
    id: 4,
    img: "./image/miencraftxbox.jpg",
    categoria: "SOFTWARE",
    nombre: "MINECRAFT",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 649,
    precioF: 899,
    iframe: "https://www.youtube.com/embed/MmB9b5njVbA?si=7Q_pD-6AVVYz_uO0",
  },
  {
    id: 5,
    img: "./image/breathnintendo.jpg",
    categoria: "SOFTWARE",
    nombre: "THE LEGEND OF ZELDA BREATH OF THE WILD",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 1099,
    precioF: 999,
    iframe: "https://www.youtube.com/embed/ofH5ptn5w-A?si=ponVlxvNpsVef4gH",
  },
];

const xboxProductosJSON = [
  {
    id: 6,
    img: "./image/haloxbox.jpg",
    categoria: "SOFTWARE",
    nombre: "HALO THE MASTER CHIEF COLLECTION",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 599,
    precioF: 899,
    iframe: "https://www.youtube.com/embed/4qBkw4YwGrM?si=5Qz0j4TgbesWl7CI",
  },
  {
    id: 7,
    img: "./image/forzaxbox.jpg",
    categoria: "SOFTWARE",
    nombre: "FORZA HORIZON 5",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 1499,
    precioF: 1699,
    iframe: "https://www.youtube.com/embed/FYH9n37B7Yw?si=TYXONogK4qp7wYJl",
  },
  {
    id: 8,
    img: "./image/gears5xbox.jpg",
    categoria: "SOFTWARE",
    nombre: "GEARS 5",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 249,
    precioF: 499,
    iframe: "https://www.youtube.com/embed/APqBWniRQbQ?si=ikqpMMSBMWmdzM_9",
  },
  {
    id: 9,
    img: "./image/hellbladexbox.jpg",
    categoria: "SOFTWARE",
    nombre: "HELLBLADE SENUAS SACRIFICE",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 399,
    precioF: 599,
    iframe: "https://www.youtube.com/embed/JRncx5UhCok?si=Rj13BJOXptyWqjGJ",
  },
  {
    id: 10,
    img: "./image/doomxbox.jpg",
    categoria: "SOFTWARE",
    nombre: "DOOM ETERNAL",
    plataforma: "XBOX SERIES X|S",
    estado: "NUEVO",
    precio: 499,
    precioF: 899,
    iframe: "https://www.youtube.com/embed/-fsz6b3IBJY?si=tcJvp-8lXCOYNo14",
  },
];

const nintendoProductosJSON = [
  {
    id: 16,
    img: "./image/oddyseysns.jpg",
    categoria: "SOFTWARE",
    nombre: "SUPER MARIO ODYSSEY",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 1199,
    precioF: 1299,
    iframe: "https://www.youtube.com/embed/5kcdRBHM7kM?si=rmrab3ltqUyjFtUC",
  },
  {
    id: 17,
    img: "./image/tearsns.jpg",
    categoria: "SOFTWARE",
    nombre: "THE LEGEND OF ZELDA TEARS OF THE KINGDOM",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 1299,
    precioF: 1499,
    iframe: "https://www.youtube.com/embed/sjxLF4IYnJc?si=B7oVXcWeV4vKJZTY",
  },
  {
    id: 18,
    img: "./image/smashns.jpg",
    categoria: "SOFTWARE",
    nombre: "SUPER SMASH BROS. ULTIMATE",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 1099,
    precioF: 1299,
    iframe: "https://www.youtube.com/embed/WShCN-AYHqA?si=eaEyp-GRfaobXDZi",
  },
  {
    id: 19,
    img: "./image/metroidns.jpg",
    categoria: "SOFTWARE",
    nombre: "METROID DREAD",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 1099,
    precioF: 1299,
    iframe: "https://www.youtube.com/embed/bbSdDDp9CNQ?si=uH7Dnk-dYg0PqE8R",
  },
  {
    id: 20,
    img: "./image/mk8dns.jpg",
    categoria: "SOFTWARE",
    nombre: "MARIO KART 8 DELUXE",
    plataforma: "NINTENDO SWITCH",
    estado: "NUEVO",
    precio: 1099,
    precioF: 1999,
    iframe: "https://www.youtube.com/embed/tKlRN2YpxRE?si=pRWRpPB5XxmMKO9y",
  },
];

const playProductosJSON = [
  {
    id: 11,
    img: "./image/spidermanps5.jpg",
    categoria: "SOFTWARE",
    nombre: "MARVELS SPIDER MAN 2",
    plataforma: "PS5",
    estado: "NUEVO",
    precio: 1299,
    precioF: 1699,
    iframe: "https://www.youtube.com/embed/rCIV0y8jNy4?si=757UntappUhj-oye",
  },
  {
    id: 12,
    img: "./image/thelastofusps5.jpg",
    categoria: "SOFTWARE",
    nombre: "THE LAST OF US PART II REMASTERED",
    plataforma: "PS5",
    estado: "NUEVO",
    precio: 1399,
    precioF: 1699,
    iframe: "https://www.youtube.com/embed/-llaUBqovHw?si=4p4GMj_BPAuhoHiq",
  },
  {
    id: 13,
    img: "./image/gowps5.jpg",
    categoria: "SOFTWARE",
    nombre: "GOD OF WAR RAGNAROK",
    plataforma: "PS5",
    estado: "NUEVO",
    precio: 1299,
    precioF: 1499,
    iframe: "https://www.youtube.com/embed/F3jePdO9_jc?si=yr9jzMUx3ExC6VB3",
  },
  {
    id: 14,
    img: "./image/ffps5.jpg",
    categoria: "SOFTWARE",
    nombre: "FINAL FANTASY VII REBIRTH",
    plataforma: "PS5",
    estado: "NUEVO",
    precio: 1349,
    precioF: 1699,
    iframe: "https://www.youtube.com/embed/DmDdbtDWSYU?si=vNbxC7wpqkVzdaLH",
  },
  {
    id: 15,
    img: "./image/horizonps5.jpg",
    categoria: "SOFTWARE",
    nombre: "HORIZON FORBIDDEN WEST",
    plataforma: "PS5",
    estado: "NUEVO",
    precio: 1499,
    precioF: 1699,
    iframe: "https://www.youtube.com/embed/9hvH3OdjdWA?si=bHRtqoqdNA3nzatw",
  },
];
